# filepath: my-helm-chart/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-registeredmodels
data:
  models.yaml: |
{{ tpl (.Files.Get "assets/models.yaml") . | indent 4 }}
  