apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-plugin-krateo
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Release.Name }}-plugin-krateo
  ports:
    - protocol: TCP
      port: {{ .Values.webservice.service.port }}
      targetPort: 8081